spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true

server:
  port: 9091
